<a href="https://colab.research.google.com/github/mbharti321/MCA5/blob/main/AI_CAT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  (1) Write a program to implement a Tic-Tac-Toe game problem using random number. 

In [31]:
# importing all necessary libraries
import numpy as np
import random
from time import sleep

# Creates an empty board
def create_board():
	return(np.array([[0, 0, 0],
                  [0, 0, 0],
                  [0, 0, 0]]))

# Check for empty places on board
def possibilities(board):
	l = []
	
	for i in range(len(board)):
		for j in range(len(board)):
			
			if board[i][j] == 0:
				l.append((i, j))
	return(l)

# Select a random place for the player
def random_place(board, player):
  selection = possibilities(board)
  #printing Empty places
  print("\n")  
  print("Current player: ", player)
  print("Avalabe spaces: ", selection)
  current_loc = random.choice(selection)  
  #printing selected loc
  print("Selected location: ", current_loc)

  board[current_loc] = player
  return(board)

# Checks whether the player has three
# of their marks in a horizontal row
def row_win(board, player):
	for x in range(len(board)):
		win = True		
		for y in range(len(board)):
			if board[x, y] != player:
				win = False
				break
				
		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a vertical row
def col_win(board, player):
	for x in range(len(board)):
		win = True
		
		for y in range(len(board)):
			if board[y][x] != player:
				win = False
				continue
				
		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a diagonal row
def diag_win(board, player):
	win = True
	y = 0
	for x in range(len(board)):
		if board[x, x] != player:
			win = False
	if win:
		return win
	win = True
	if win:
		for x in range(len(board)):
			y = len(board) - 1 - x
			if board[x, y] != player:
				win = False
	return win

# Evaluates whether there is
# a winner or a tie
def evaluate(board):
	winner = 0
	
	for player in [1, 2]:
		if (row_win(board, player) or
			col_win(board,player) or
			diag_win(board,player)):
				
			winner = player
	#if all locatin in board is full, then return -1, indicating draw		
	if np.all(board != 0) and winner == 0:
		winner = -1
	return winner

# Main function to start the game
def play_game():
  board, winner, counter = create_board(), 0, 1
  # print()
  print(board)
  sleep(1)

  while winner == 0:
    for player in [1, 2]:
      board = random_place(board, player)
      print("~~~~~~~~~\nBoard after move ", str(counter) , ",")
      print(board)
      sleep(1.5)
      counter += 1
      winner = evaluate(board)
      if winner != 0:
        break
  return(winner)
	
	

# Driver Code
result = play_game()
if result == -1:
  print("\nThe game is draw.")
else:
  print("\nWinner is: ", result)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


Current player:  1
Avalabe spaces:  [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
Selected location:  (1, 0)
~~~~~~~~~
Board after move  1 ,
[[0 0 0]
 [1 0 0]
 [0 0 0]]


Current player:  2
Avalabe spaces:  [(0, 0), (0, 1), (0, 2), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
Selected location:  (1, 1)
~~~~~~~~~
Board after move  2 ,
[[0 0 0]
 [1 2 0]
 [0 0 0]]


Current player:  1
Avalabe spaces:  [(0, 0), (0, 1), (0, 2), (1, 2), (2, 0), (2, 1), (2, 2)]
Selected location:  (0, 2)
~~~~~~~~~
Board after move  3 ,
[[0 0 1]
 [1 2 0]
 [0 0 0]]


Current player:  2
Avalabe spaces:  [(0, 0), (0, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
Selected location:  (1, 2)
~~~~~~~~~
Board after move  4 ,
[[0 0 1]
 [1 2 2]
 [0 0 0]]


Current player:  1
Avalabe spaces:  [(0, 0), (0, 1), (2, 0), (2, 1), (2, 2)]
Selected location:  (2, 1)
~~~~~~~~~
Board after move  5 ,
[[0 0 1]
 [1 2 2]
 [0 1 0]]


Current player:  2
Avalabe spaces:  [(0, 0), (0, 1), (2, 0),

# (2) Write a program to implement 8-Queen Problem with heuristic function using any local search algorithm. 
Suppose we generalize the eight-queens problem to the N-queens problem, where the task is to place N queens on an N by N chessboard. How must the programs be changed? It is clear that there are values for N for which no solution exists (consider N=2 or N=3, for example). What happens when your program is executed for these values? How might you produce more meaningful output? 

In [2]:
import random

def random_chromosome(size): #making random chromosomes 
    return [ random.randint(1, nq) for _ in range(nq) ]

def fitness(chromosome):
    horizontal_collisions = sum([chromosome.count(queen)-1 for queen in chromosome])/2
    diagonal_collisions = 0

    n = len(chromosome)
    left_diagonal = [0] * 2*n
    right_diagonal = [0] * 2*n
    for i in range(n):
        left_diagonal[i + chromosome[i] - 1] += 1
        right_diagonal[len(chromosome) - i + chromosome[i] - 2] += 1

    diagonal_collisions = 0
    for i in range(2*n-1):
        counter = 0
        if left_diagonal[i] > 1:
            counter += left_diagonal[i]-1
        if right_diagonal[i] > 1:
            counter += right_diagonal[i]-1
        diagonal_collisions += counter / (n-abs(i-n+1))
    
    return int(maxFitness - (horizontal_collisions + diagonal_collisions)) #28-(2+3)=23

def probability(chromosome, fitness):
    return fitness(chromosome) / maxFitness

def random_pick(population, probabilities):
    populationWithProbabilty = zip(population, probabilities)
    total = sum(w for c, w in populationWithProbabilty)
    r = random.uniform(0, total)
    upto = 0
    for c, w in zip(population, probabilities):
        if upto + w >= r:
            return c
        upto += w
    assert False, "Shouldn't get here"
        
def reproduce(x, y): #doing cross_over between two chromosomes
    n = len(x)
    c = random.randint(0, n - 1)
    return x[0:c] + y[c:n]

def mutate(x):  #randomly changing the value of a random index of a chromosome
    n = len(x)
    c = random.randint(0, n - 1)
    m = random.randint(1, n)
    x[c] = m
    return x

def genetic_queen(population, fitness):
    mutation_probability = 0.03
    new_population = []
    probabilities = [probability(n, fitness) for n in population]
    for i in range(len(population)):
        x = random_pick(population, probabilities) #best chromosome 1
        y = random_pick(population, probabilities) #best chromosome 2
        child = reproduce(x, y) #creating two new chromosomes from the best 2 chromosomes
        if random.random() < mutation_probability:
            child = mutate(child)
        print_chromosome(child)
        new_population.append(child)
        if fitness(child) == maxFitness: break
    return new_population

def print_chromosome(chrom):
    print("Chromosome = {},  Fitness = {}"
        .format(str(chrom), fitness(chrom)))

if __name__ == "__main__":
    nq = int(input("Enter Number of Queens: ")) #say N = 8
    
    # checking if the user input is 2 or 3
    if nq in (2,3):
      print("For ", nq, ", there is no solution." )
      print("Pleaase try with more queens!!")
      # exit(0)
      !kill -9 -1

    maxFitness = (nq*(nq-1))/2  # 8*7/2 = 28
    population = [random_chromosome(nq) for _ in range(100)]
    
    generation = 1

    while not maxFitness in [fitness(chrom) for chrom in population]:
        print("=== Generation {} ===".format(generation))
        population = genetic_queen(population, fitness)
        print("")
        print("Maximum Fitness = {}".format(max([fitness(n) for n in population])))
        generation += 1
    chrom_out = []
    print("Solved in Generation {}!".format(generation-1))
    for chrom in population:
        if fitness(chrom) == maxFitness:
            print("");
            print("One of the solutions: ")
            chrom_out = chrom
            print_chromosome(chrom)
            
    board = []

    for x in range(nq):
        board.append(["x"] * nq)
        
    for i in range(nq):
        board[nq-chrom_out[i]][i]="Q"
            

    def print_board(board):
        for row in board:
            print (" ".join(row))
            
    print()
    print_board(board)

Enter Number of Queens: 4
=== Generation 1 ===
Chromosome = [1, 2, 4, 3],  Fitness = 5
Chromosome = [4, 2, 3, 3],  Fitness = 4
Chromosome = [1, 2, 4, 1],  Fitness = 4
Chromosome = [2, 2, 3, 2],  Fitness = 2
Chromosome = [2, 3, 3, 1],  Fitness = 4
Chromosome = [2, 4, 3, 3],  Fitness = 4
Chromosome = [3, 4, 2, 4],  Fitness = 4
Chromosome = [3, 4, 2, 2],  Fitness = 4
Chromosome = [1, 3, 1, 4],  Fitness = 4
Chromosome = [4, 3, 2, 4],  Fitness = 4
Chromosome = [4, 2, 1, 3],  Fitness = 5
Chromosome = [2, 3, 2, 2],  Fitness = 2
Chromosome = [1, 4, 2, 2],  Fitness = 4
Chromosome = [2, 1, 2, 2],  Fitness = 2
Chromosome = [3, 3, 3, 2],  Fitness = 2
Chromosome = [1, 2, 4, 2],  Fitness = 4
Chromosome = [1, 4, 1, 3],  Fitness = 5
Chromosome = [2, 4, 3, 1],  Fitness = 5
Chromosome = [4, 4, 2, 4],  Fitness = 2
Chromosome = [4, 4, 2, 3],  Fitness = 4
Chromosome = [4, 2, 4, 3],  Fitness = 4
Chromosome = [3, 1, 2, 4],  Fitness = 5
Chromosome = [3, 2, 4, 2],  Fitness = 4
Chromosome = [4, 1, 1, 4],  Fitne

# Interpretation
**For N=2 or N=3,**
we are  checking manually in code, if the user input is 2 or 3. In that case, we are printing that there is no solution for that perticular input.



```
# checking if the user input is 2 or 3
if nq in (2,3):
      print("For ", nq, ", there is no solution." )
      print("Pleaase try with more queens!!")
      quit()
```
So, using this code block, we are stoping program from infinite execution.


In [ ]:

# import sys
import os
nq = int(input("Enter Number of Queens: ")) #say N = 8
    
# checking if the user input is 2 or 3
if nq in (2,3):
  print("For ", nq, ", there is no solution." )
  print("Pleaase try with more queens!!")
  # exit(1)
  # raise SystemExit
  # sys.exit
  # os._exit()
  # !kill -9 -1
  import sys
  sys.exit()
print("hello")